title: Hello, world! I'm Koreanssam
description: > # this means to ignore newlines until "baseurl:"
  교육과 AI를 중심으로 한 교사 이성원의 블로그입니다.
  교육에 관련된 다양한 주제와 AI 기술을 활용한 교육에 대한 내용을 다룰 예정이니 많은 관심 부탁드립니다.
permalink: ':title/'
baseurl: "https://koreanssam.github.io" # the subpath of your site, e.g. /blog
url: "https://koreanssam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 이성원 # add your name
author-img: 이성원.jpg # add your photo
about-author: AI에 관심이 많은 개발하는 국어 교사 이성원입니다.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: koreanssam # add your Github handle
social-linkedin: koreanssam # add your Linkedin handle
social-email: 0koreanssam0@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
